IP 13
friends-library/isaac-penington pull request #95
Opened 2020-09-03 14:47 UTC by maijapapaya

@jaredh159 @Henderjay

2020-09-03 14:48 UTC, maijapapaya commented
I wasn't sure if this was a truly a letter or not, so I wasn't sure about my use of a postscript, especially because the postscript is dated before the letter is.

2020-09-03 18:46 UTC, jaredh159 requested changes
Looks great, just one little change. 👍

2020-09-03 18:46 UTC, jaredh159 commented on unabridged-works-volume-4/original/13-compulsion-in-religion.adoc
>  Query 5. Whether under the law of Moses,
Looks like all of the other `Query X.` you italicized, but not this one.

2020-09-04 14:16 UTC, jaredh159 approved these changes

2020-09-04 14:16 UTC, merged

2020-09-04 14:16 UTC, jaredh159 commented
thanks!